name: Release if bump version number

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  check-bump-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.diff.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Get version number diff
        run: |
          version="$(git diff ${{ github.event.before }}..${{ github.event.after }} package.json | sed -nr '/^\+ +\"version\":/p' | sed -r 's/^.*\"([0-9a-z\.\-\+]+)\"*.$/\1/')"
          echo "::set-output name=version::$version"
        id: diff

  release:
    needs: check-bump-version
    if: ${{ needs.check-bump-version.outputs.new-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: v${{ needs.check-bump-version.outputs.new-version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # After tagged, openupm.com gets the tag and automatically publishes the UPM package.
